var searchData=
[
  ['rūšiavimo_20strategiją_0',['Rūšiavimo strategiją',['../md__r_e_a_d_m_e.html#autotoc_md7',1,'Darbo su deque&apos;ais rezultatai, naudojant 1 rūšiavimo strategiją'],['../md__r_e_a_d_m_e.html#autotoc_md6',1,'Darbo su list&apos;ais rezultatai, naudojant 1 rūšiavimo strategiją'],['../md__r_e_a_d_m_e.html#autotoc_md5',1,'Darbo su vektoriais rezultatai, naudojant 1 rūšiavimo strategiją']]],
  ['release_20ai_1',['Release&apos;ai',['../md__r_e_a_d_m_e.html#autotoc_md1',1,'']]],
  ['rezultatai_2',['Testavimo funkcijos rezultatai',['../md__r_e_a_d_m_e.html#autotoc_md21',1,'']]],
  ['rezultatai_20naudojant_201_20rūšiavimo_20strategiją_3',['Rezultatai naudojant 1 rūšiavimo strategiją',['../md__r_e_a_d_m_e.html#autotoc_md7',1,'Darbo su deque&apos;ais rezultatai, naudojant 1 rūšiavimo strategiją'],['../md__r_e_a_d_m_e.html#autotoc_md6',1,'Darbo su list&apos;ais rezultatai, naudojant 1 rūšiavimo strategiją'],['../md__r_e_a_d_m_e.html#autotoc_md5',1,'Darbo su vektoriais rezultatai, naudojant 1 rūšiavimo strategiją']]],
  ['rezultatai_20naudojant_202_20strategija_4',['Rezultatai naudojant 2 strategija',['../md__r_e_a_d_m_e.html#autotoc_md12',1,'Deque esanciu studentu rikiavimo rezultatai naudojant 2 strategija'],['../md__r_e_a_d_m_e.html#autotoc_md10',1,'List&apos;e esanciu studentu rikiavimo rezultatai naudojant 2 strategija'],['../md__r_e_a_d_m_e.html#autotoc_md8',1,'Vektoriuje esanciu studentu rikiavimo rezultatai naudojant 2 strategija']]],
  ['rezultatai_20naudojant_203_20strategija_5',['Rezultatai naudojant 3 strategija',['../md__r_e_a_d_m_e.html#autotoc_md13',1,'Deque esanciu studentu rikiavimo rezultatai naudojant 3 strategija'],['../md__r_e_a_d_m_e.html#autotoc_md11',1,'List&apos;e esanciu studentu rikiavimo rezultatai naudojant 3 strategija'],['../md__r_e_a_d_m_e.html#autotoc_md9',1,'Vektoriuje esanciu studentu rikiavimo rezultatai naudojant 3 strategija']]],
  ['rikiavimo_20rezultatai_20naudojant_202_20strategija_6',['Rikiavimo rezultatai naudojant 2 strategija',['../md__r_e_a_d_m_e.html#autotoc_md12',1,'Deque esanciu studentu rikiavimo rezultatai naudojant 2 strategija'],['../md__r_e_a_d_m_e.html#autotoc_md10',1,'List&apos;e esanciu studentu rikiavimo rezultatai naudojant 2 strategija'],['../md__r_e_a_d_m_e.html#autotoc_md8',1,'Vektoriuje esanciu studentu rikiavimo rezultatai naudojant 2 strategija']]],
  ['rikiavimo_20rezultatai_20naudojant_203_20strategija_7',['Rikiavimo rezultatai naudojant 3 strategija',['../md__r_e_a_d_m_e.html#autotoc_md13',1,'Deque esanciu studentu rikiavimo rezultatai naudojant 3 strategija'],['../md__r_e_a_d_m_e.html#autotoc_md11',1,'List&apos;e esanciu studentu rikiavimo rezultatai naudojant 3 strategija'],['../md__r_e_a_d_m_e.html#autotoc_md9',1,'Vektoriuje esanciu studentu rikiavimo rezultatai naudojant 3 strategija']]],
  ['rule_20of_20five_20pritaikymas_8',['Rule Of Five Pritaikymas',['../md__r_e_a_d_m_e.html#autotoc_md20',1,'']]]
];
