var searchData=
[
  ['strategiją_0',['Strategiją',['../md__r_e_a_d_m_e.html#autotoc_md7',1,'Darbo su deque&apos;ais rezultatai, naudojant 1 rūšiavimo strategiją'],['../md__r_e_a_d_m_e.html#autotoc_md6',1,'Darbo su list&apos;ais rezultatai, naudojant 1 rūšiavimo strategiją'],['../md__r_e_a_d_m_e.html#autotoc_md5',1,'Darbo su vektoriais rezultatai, naudojant 1 rūšiavimo strategiją']]],
  ['strategija_1',['Strategija',['../md__r_e_a_d_m_e.html#autotoc_md12',1,'Deque esanciu studentu rikiavimo rezultatai naudojant 2 strategija'],['../md__r_e_a_d_m_e.html#autotoc_md13',1,'Deque esanciu studentu rikiavimo rezultatai naudojant 3 strategija'],['../md__r_e_a_d_m_e.html#autotoc_md10',1,'List&apos;e esanciu studentu rikiavimo rezultatai naudojant 2 strategija'],['../md__r_e_a_d_m_e.html#autotoc_md11',1,'List&apos;e esanciu studentu rikiavimo rezultatai naudojant 3 strategija'],['../md__r_e_a_d_m_e.html#autotoc_md8',1,'Vektoriuje esanciu studentu rikiavimo rezultatai naudojant 2 strategija'],['../md__r_e_a_d_m_e.html#autotoc_md9',1,'Vektoriuje esanciu studentu rikiavimo rezultatai naudojant 3 strategija']]],
  ['struct_2',['Struct',['../md__r_e_a_d_m_e.html#autotoc_md14',1,'Programos veikimo laikų palyginimas naudojant Class ir Struct'],['../md__r_e_a_d_m_e.html#autotoc_md15',1,'Struct']]],
  ['studentų_20kiekis_3a_20100000_3',['Studentų kiekis: 100000',['../md__r_e_a_d_m_e.html#autotoc_md18',1,'']]],
  ['studentų_20kiekis_3a_201000000_4',['Studentų kiekis: 1000000',['../md__r_e_a_d_m_e.html#autotoc_md19',1,'']]],
  ['studentas_5',['studentas',['../classstudentas.html',1,'']]],
  ['studentu_20rikiavimo_20rezultatai_20naudojant_202_20strategija_6',['Studentu rikiavimo rezultatai naudojant 2 strategija',['../md__r_e_a_d_m_e.html#autotoc_md12',1,'Deque esanciu studentu rikiavimo rezultatai naudojant 2 strategija'],['../md__r_e_a_d_m_e.html#autotoc_md10',1,'List&apos;e esanciu studentu rikiavimo rezultatai naudojant 2 strategija'],['../md__r_e_a_d_m_e.html#autotoc_md8',1,'Vektoriuje esanciu studentu rikiavimo rezultatai naudojant 2 strategija']]],
  ['studentu_20rikiavimo_20rezultatai_20naudojant_203_20strategija_7',['Studentu rikiavimo rezultatai naudojant 3 strategija',['../md__r_e_a_d_m_e.html#autotoc_md13',1,'Deque esanciu studentu rikiavimo rezultatai naudojant 3 strategija'],['../md__r_e_a_d_m_e.html#autotoc_md11',1,'List&apos;e esanciu studentu rikiavimo rezultatai naudojant 3 strategija'],['../md__r_e_a_d_m_e.html#autotoc_md9',1,'Vektoriuje esanciu studentu rikiavimo rezultatai naudojant 3 strategija']]],
  ['su_20deque_20ais_20rezultatai_20naudojant_201_20rūšiavimo_20strategiją_8',['Darbo su deque&apos;ais rezultatai, naudojant 1 rūšiavimo strategiją',['../md__r_e_a_d_m_e.html#autotoc_md7',1,'']]],
  ['su_20list_20ais_20rezultatai_20naudojant_201_20rūšiavimo_20strategiją_9',['Darbo su list&apos;ais rezultatai, naudojant 1 rūšiavimo strategiją',['../md__r_e_a_d_m_e.html#autotoc_md6',1,'']]],
  ['su_20vektoriais_20rezultatai_20naudojant_201_20rūšiavimo_20strategiją_10',['Darbo su vektoriais rezultatai, naudojant 1 rūšiavimo strategiją',['../md__r_e_a_d_m_e.html#autotoc_md5',1,'']]]
];
