var searchData=
[
  ['savo_20vector_20klasės_20implementacija_0',['Savo Vector klasės implementacija',['../md__r_e_a_d_m_e.html#autotoc_md28',1,'']]],
  ['spartos_20palyginimas_1',['Spartos palyginimas',['../md__r_e_a_d_m_e.html#autotoc_md31',1,'std::vector vs. Vector konteineriu darbo su studentu failais spartos palyginimas'],['../md__r_e_a_d_m_e.html#autotoc_md30',1,'std::vector vs. Vector konteineriu uzpildymo spartos palyginimas']]],
  ['std_3a_3avector_20vs_20vector_20konteineriu_20darbo_20su_20studentu_20failais_20spartos_20palyginimas_2',['std::vector vs. Vector konteineriu darbo su studentu failais spartos palyginimas',['../md__r_e_a_d_m_e.html#autotoc_md31',1,'']]],
  ['std_3a_3avector_20vs_20vector_20konteineriu_20uzpildymo_20spartos_20palyginimas_3',['std::vector vs. Vector konteineriu uzpildymo spartos palyginimas',['../md__r_e_a_d_m_e.html#autotoc_md30',1,'']]],
  ['strategiją_4',['Strategiją',['../md__r_e_a_d_m_e.html#autotoc_md7',1,'Darbo su deque&apos;ais rezultatai, naudojant 1 rūšiavimo strategiją'],['../md__r_e_a_d_m_e.html#autotoc_md6',1,'Darbo su list&apos;ais rezultatai, naudojant 1 rūšiavimo strategiją'],['../md__r_e_a_d_m_e.html#autotoc_md5',1,'Darbo su vektoriais rezultatai, naudojant 1 rūšiavimo strategiją']]],
  ['strategija_5',['Strategija',['../md__r_e_a_d_m_e.html#autotoc_md12',1,'Deque esanciu studentu rikiavimo rezultatai naudojant 2 strategija'],['../md__r_e_a_d_m_e.html#autotoc_md13',1,'Deque esanciu studentu rikiavimo rezultatai naudojant 3 strategija'],['../md__r_e_a_d_m_e.html#autotoc_md10',1,'List&apos;e esanciu studentu rikiavimo rezultatai naudojant 2 strategija'],['../md__r_e_a_d_m_e.html#autotoc_md11',1,'List&apos;e esanciu studentu rikiavimo rezultatai naudojant 3 strategija'],['../md__r_e_a_d_m_e.html#autotoc_md8',1,'Vektoriuje esanciu studentu rikiavimo rezultatai naudojant 2 strategija'],['../md__r_e_a_d_m_e.html#autotoc_md9',1,'Vektoriuje esanciu studentu rikiavimo rezultatai naudojant 3 strategija']]],
  ['struct_6',['Struct',['../md__r_e_a_d_m_e.html#autotoc_md14',1,'Programos veikimo laikų palyginimas naudojant Class ir Struct'],['../md__r_e_a_d_m_e.html#autotoc_md15',1,'Struct']]],
  ['studentų_20kiekis_3a_20100000_7',['Studentų kiekis: 100000',['../md__r_e_a_d_m_e.html#autotoc_md18',1,'']]],
  ['studentų_20kiekis_3a_201000000_8',['Studentų kiekis: 1000000',['../md__r_e_a_d_m_e.html#autotoc_md19',1,'']]],
  ['studentas_9',['studentas',['../classstudentas.html',1,'']]],
  ['studentu_20failais_20spartos_20palyginimas_10',['std::vector vs. Vector konteineriu darbo su studentu failais spartos palyginimas',['../md__r_e_a_d_m_e.html#autotoc_md31',1,'']]],
  ['studentu_20rikiavimo_20rezultatai_20naudojant_202_20strategija_11',['Studentu rikiavimo rezultatai naudojant 2 strategija',['../md__r_e_a_d_m_e.html#autotoc_md12',1,'Deque esanciu studentu rikiavimo rezultatai naudojant 2 strategija'],['../md__r_e_a_d_m_e.html#autotoc_md10',1,'List&apos;e esanciu studentu rikiavimo rezultatai naudojant 2 strategija'],['../md__r_e_a_d_m_e.html#autotoc_md8',1,'Vektoriuje esanciu studentu rikiavimo rezultatai naudojant 2 strategija']]],
  ['studentu_20rikiavimo_20rezultatai_20naudojant_203_20strategija_12',['Studentu rikiavimo rezultatai naudojant 3 strategija',['../md__r_e_a_d_m_e.html#autotoc_md13',1,'Deque esanciu studentu rikiavimo rezultatai naudojant 3 strategija'],['../md__r_e_a_d_m_e.html#autotoc_md11',1,'List&apos;e esanciu studentu rikiavimo rezultatai naudojant 3 strategija'],['../md__r_e_a_d_m_e.html#autotoc_md9',1,'Vektoriuje esanciu studentu rikiavimo rezultatai naudojant 3 strategija']]],
  ['su_20deque_20ais_20rezultatai_20naudojant_201_20rūšiavimo_20strategiją_13',['Darbo su deque&apos;ais rezultatai, naudojant 1 rūšiavimo strategiją',['../md__r_e_a_d_m_e.html#autotoc_md7',1,'']]],
  ['su_20list_20ais_20rezultatai_20naudojant_201_20rūšiavimo_20strategiją_14',['Darbo su list&apos;ais rezultatai, naudojant 1 rūšiavimo strategiją',['../md__r_e_a_d_m_e.html#autotoc_md6',1,'']]],
  ['su_20studentu_20failais_20spartos_20palyginimas_15',['std::vector vs. Vector konteineriu darbo su studentu failais spartos palyginimas',['../md__r_e_a_d_m_e.html#autotoc_md31',1,'']]],
  ['su_20vektoriais_20rezultatai_20naudojant_201_20rūšiavimo_20strategiją_16',['Darbo su vektoriais rezultatai, naudojant 1 rūšiavimo strategiją',['../md__r_e_a_d_m_e.html#autotoc_md5',1,'']]]
];
